package com.zouliangyu.lol.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.zouliangyu.lol.greendao.Article;
import com.zouliangyu.lol.greendao.Hero;

import com.zouliangyu.lol.greendao.ArticleDao;
import com.zouliangyu.lol.greendao.HeroDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig articleDaoConfig;
    private final DaoConfig heroDaoConfig;

    private final ArticleDao articleDao;
    private final HeroDao heroDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        articleDaoConfig = daoConfigMap.get(ArticleDao.class).clone();
        articleDaoConfig.initIdentityScope(type);

        heroDaoConfig = daoConfigMap.get(HeroDao.class).clone();
        heroDaoConfig.initIdentityScope(type);

        articleDao = new ArticleDao(articleDaoConfig, this);
        heroDao = new HeroDao(heroDaoConfig, this);

        registerDao(Article.class, articleDao);
        registerDao(Hero.class, heroDao);
    }
    
    public void clear() {
        articleDaoConfig.getIdentityScope().clear();
        heroDaoConfig.getIdentityScope().clear();
    }

    public ArticleDao getArticleDao() {
        return articleDao;
    }

    public HeroDao getHeroDao() {
        return heroDao;
    }

}
