package com.zouliangyu.lol.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "HERO".
 */
public class Hero {

    private Long id;
    private String imageUrl;
    private String code;
    private String enName;

    public Hero() {
    }

    public Hero(Long id) {
        this.id = id;
    }

    public Hero(Long id, String imageUrl, String code, String enName) {
        this.id = id;
        this.imageUrl = imageUrl;
        this.code = code;
        this.enName = enName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getEnName() {
        return enName;
    }

    public void setEnName(String enName) {
        this.enName = enName;
    }

}
